### ISSUE TITLE
TabShell Tasks

### ISSUE THREAD

**Issue by henriquetied472** [Henriquetied472/tabshell-cli#1]
# TabShell

- [x] **Orquestrador**
    - [x] Pegar o ***Input*** do usuário  usando o pacote [**Survey**](https://github.com/AlecAivazis/survey)
    - [x] Requisitar os dados da ***API***
    - [x] Formatar os dados para apresentação
    - [x] Exibir de maneira confortavel e correta no terminal usando o pacote [**Go Term Markdown**](https://github.com/MichaelMure/go-term-markdown) e [**PTerm**](https://github.com/pterm/pterm)

- [x] **Questionario**
    - [x] Elaborar os questionamentos de acordo com o requerido
    - [x] Capturar a escolhado usuário
    - [x] Enviar ao **Requesitor da *API***
    - [x] Enviar os dados para o **Sanetizador**

- [x] **Requesitor da *API***
    - [x] Buscar os dados da ***API***

- [x] **Sanitizador/Renderizador**
    - [x] Formatar texto de acordo com o MarkDown
    - [x] Imprimir os dados formatados usando cores, negrito, *etc* no terminal

**Comment by filipedeschamps** [comment]
Sensacional @Henriquetied472 ! Estou muito curioso em saber como esse projeto irá evoluir e como ficará a usabilidade interface, incluindo como você irá interpretar no terminal a formatação do markdown. Detona, porque tem altíssima margem para ficar muito massa!!!

Em paralelo, sugiro verificar se a escrita do `Sanetizador` é assim, ou se é `Sanitizador`.

**Comment by henriquetied472** [comment]
> Sensacional @Henriquetied472 ! Estou muito curioso em saber como esse projeto irá evoluir e como ficará a usabilidade interface, incluindo como você irá interpretar no terminal a formatação do markdown. Detona, porque tem altíssima margem para ficar muito massa!!!
> 
> Em paralelo, sugiro verificar se a escrita do `Sanetizador` é assim, ou se é `Sanitizador`.

Obrigado e espero a mesma coisa
É `Sanitizador` mesmo e já corrigi
