### ISSUE TITLE
Remover builds do repo

### ISSUE THREAD

**Issue by tashima42** [Henriquetied472/tabshell-cli#8]
E ae Henrique, acho que não é uma boa ideia deixar as builds no repositório, isso vai deixar ele desnecessariamente pesado e só vai aumentar e aumentar a cada nova versão.
O mesmo para os logs.

Você poderia usar a feature de releases do Github pra hospedar esses executáveis: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by henriquetied472** [comment]
Obrigado pela dica, irei usá-la, porém, não conseguirei agora pois estou sem o computador, mas irei usá-la assim que possível

**Comment by tashima42** [comment]
Boa, @Henriquetied472. Posso fazer uma build pro M1, darwin/arm64 se tu me der uma ajuda pra ter ctz que ta tudo ok.

**Comment by henriquetied472** [comment]
Com certeza eu adoraria ter uma build para o M1, porem, o Go tem cross-compiling, aqui no Linux eu consigo fazer a build darwin/arm64
